export interface CatalogCategory {
  slug: string
  name: string
  description: string
  color: string
  sortOrder: number
}

export interface CatalogService {
  slug: string
  categorySlug: string
  agendaSourceId: number | null
  name: string
  description: string | null
  durationMinutes: number
  priceCents: number
  priceNote: string | null
  color: string
  sortOrder: number
  isBookable: boolean
  sourceImageUrl: string | null
}

export const catalogCategories: CatalogCategory[] = [
  {
    slug: 'laser-erbium',
    name: 'Laser Erbium',
    description:
      'Resurfaçage cutané non ablatif pour rides, cicatrices et taches.',
    color: '#927b59',
    sortOrder: 0,
  },
  {
    slug: 'onglerie',
    name: 'Onglerie',
    description:
      'Pose complète, remplissage, semi-permanent et dépose soignée.',
    color: '#927b59',
    sortOrder: 1,
  },
  {
    slug: 'soins-visage',
    name: 'Soins visage',
    description: 'Soins bio et RHEA ainsi que peelings professionnels.',
    color: '#927b59',
    sortOrder: 2,
  },
  {
    slug: 'endospheres-therapy',
    name: 'Endosphères Therapy',
    description: 'Remodelage et raffermissement du visage et du corps.',
    color: '#927b59',
    sortOrder: 3,
  },
  {
    slug: 'sourcils-cils',
    name: 'Sourcils & Cils',
    description: 'Teintures, microblading et microshading.',
    color: '#927b59',
    sortOrder: 4,
  },
  {
    slug: 'epilation-au-fil',
    name: 'Épilation au fil',
    description: 'Technique douce et précise pour sourcils, lèvre et visage.',
    color: '#927b59',
    sortOrder: 5,
  },
  {
    slug: 'epilation-dielectrique',
    name: 'Épilation diélectrique',
    description: 'Épilation de précision facturée à la minute.',
    color: '#927b59',
    sortOrder: 6,
  },
  {
    slug: 'epilation-laser',
    name: 'Épilation laser',
    description:
      'Épilation laser pour différentes zones du visage et du corps.',
    color: '#927b59',
    sortOrder: 7,
  },
]

export const catalogServices: CatalogService[] = [
  {
    slug: 'laser-erbium-petite-zone',
    categorySlug: 'laser-erbium',
    agendaSourceId: 99206,
    name: 'Petite zone',
    description:
      'Rides localisées, cicatrices, mains, lèvres, autour de la bouche ou menton. Les résultats apparaissent progressivement, généralement après 2 à 3 séances espacées de 3 à 4 semaines.',
    durationMinutes: 30,
    priceCents: 18000,
    priceNote: null,
    color: '#fff9c4',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/6911/original/pics_pages_peeling_laser_2.png?1747840566',
  },
  {
    slug: 'laser-erbium-visage',
    categorySlug: 'laser-erbium',
    agendaSourceId: 99223,
    name: 'Visage',
    description:
      'Les résultats apparaissent progressivement, généralement après 2 à 3 séances espacées de 3 à 4 semaines.',
    durationMinutes: 60,
    priceCents: 38000,
    priceNote: null,
    color: '#ffeb3b',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/6939/original/1000157420.jpg?1747897417',
  },
  {
    slug: 'laser-erbium-grande-zone',
    categorySlug: 'laser-erbium',
    agendaSourceId: 99203,
    name: 'Grande zone',
    description:
      'Relissage global, taches, rides profondes, ventre ou fesses. Les résultats apparaissent progressivement, généralement après 2 à 3 séances espacées de 3 à 4 semaines.',
    durationMinutes: 120,
    priceCents: 65000,
    priceNote: null,
    color: '#fff176',
    sortOrder: 2,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/6910/original/pics_pages_peeling_laser_2_(1).png?1747840713',
  },
  {
    slug: 'laser-erbium-visage-cou-decollete',
    categorySlug: 'laser-erbium',
    agendaSourceId: 101969,
    name: 'Visage + cou + décolleté',
    description:
      'Les résultats apparaissent progressivement, généralement après 2 à 3 séances espacées de 3 à 4 semaines.',
    durationMinutes: 120,
    priceCents: 58000,
    priceNote: null,
    color: '#fbc02d',
    sortOrder: 3,
    isBookable: true,
    sourceImageUrl: null,
  },
  {
    slug: 'onglerie-pose-complete',
    categorySlug: 'onglerie',
    agendaSourceId: 84578,
    name: 'Pose complète',
    description: null,
    durationMinutes: 120,
    priceCents: 10000,
    priceNote: null,
    color: '#d1c4e9',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/12003/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_13.06.17.png?1709035735',
  },
  {
    slug: 'onglerie-remplissage',
    categorySlug: 'onglerie',
    agendaSourceId: 84579,
    name: 'Remplissage',
    description: null,
    durationMinutes: 90,
    priceCents: 7500,
    priceNote: null,
    color: '#b39ddb',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/4641/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_13.06.06.png?1709035793',
  },
  {
    slug: 'onglerie-semi-permanent',
    categorySlug: 'onglerie',
    agendaSourceId: 84580,
    name: 'Semi-permanent',
    description: null,
    durationMinutes: 60,
    priceCents: 6000,
    priceNote: null,
    color: '#9575cd',
    sortOrder: 2,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/12014/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_13.06.35.png?1709035858',
  },
  {
    slug: 'onglerie-depose',
    categorySlug: 'onglerie',
    agendaSourceId: 84581,
    name: 'Dépose',
    description: null,
    durationMinutes: 40,
    priceCents: 3000,
    priceNote: null,
    color: '#7e57c2',
    sortOrder: 3,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/12018/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_13.11.44.png?1709035936',
  },
  {
    slug: 'soin-visage-bio',
    categorySlug: 'soins-visage',
    agendaSourceId: 84650,
    name: 'Soin visage bio',
    description:
      'Découvrez notre soin du visage exclusif, utilisant des produits bio pour une expérience naturelle et apaisante.',
    durationMinutes: 90,
    priceCents: 12000,
    priceNote: 'Teinture des cils et sourcils : 20 CHF chacun avec le soin',
    color: '#4f6f39',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/12392/original/shutterstock_119713084_(Copier).jpg?1709110340',
  },
  {
    slug: 'soin-visage-rhea',
    categorySlug: 'soins-visage',
    agendaSourceId: 101540,
    name: 'Soin visage RHEA',
    description: null,
    durationMinutes: 90,
    priceCents: 14000,
    priceNote: null,
    color: '#4f6f39',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/6209/original/shutterstock_119713084_(Copier).jpg?1755777227',
  },
  {
    slug: 'peeling-milk',
    categorySlug: 'soins-visage',
    agendaSourceId: 86084,
    name: 'Peeling milk',
    description: null,
    durationMinutes: 30,
    priceCents: 15000,
    priceNote: 'La séance',
    color: '#e53935',
    sortOrder: 2,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/2838/original/Capture_d%E2%80%99e%CC%81cran_2024-04-15_a%CC%80_16.07.30.png?1713191407',
  },
  {
    slug: 'peeling-cristal',
    categorySlug: 'soins-visage',
    agendaSourceId: 86009,
    name: 'Peeling cristal',
    description: null,
    durationMinutes: 30,
    priceCents: 20000,
    priceNote: 'La séance',
    color: '#a8adcb',
    sortOrder: 3,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/14825/original/Capture_d%E2%80%99e%CC%81cran_2024-04-15_a%CC%80_16.06.13.png?1713191328',
  },
  {
    slug: 'peeling-tca',
    categorySlug: 'soins-visage',
    agendaSourceId: 86085,
    name: 'Peeling TCA',
    description: null,
    durationMinutes: 30,
    priceCents: 25000,
    priceNote: 'La séance',
    color: '#ef9a9a',
    sortOrder: 4,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/2788/original/Capture_d%E2%80%99e%CC%81cran_2024-04-15_a%CC%80_16.08.35.png?1713191491',
  },
  {
    slug: 'endospheres-visage',
    categorySlug: 'endospheres-therapy',
    agendaSourceId: 87624,
    name: 'Visage',
    description:
      'Eva by Endospheres® est un traitement conçu pour les soins du visage. Ses trois dispositifs réalisent chaque phase, de l’exfoliation à la répartition profonde des nutriments.',
    durationMinutes: 15,
    priceCents: 9000,
    priceNote: null,
    color: '#a1887f',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/1836/original/Capture_d%E2%80%99e%CC%81cran_2024-05-28_a%CC%80_10.15.29.png?1716884206',
  },
  {
    slug: 'endospheres-corps',
    categorySlug: 'endospheres-therapy',
    agendaSourceId: 87623,
    name: 'Corps',
    description:
      'La philosophie du traitement Endospheres® est celle d’une beauté qui part de l’intérieur de l’organisme, sans les effets artificiels de méthodes plus invasives.',
    durationMinutes: 45,
    priceCents: 16000,
    priceNote: null,
    color: '#a1887f',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/1837/original/Capture_d%E2%80%99e%CC%81cran_2024-05-28_a%CC%80_10.15.29.png?1716884150',
  },
  {
    slug: 'sourcils-cils-teinture-cils',
    categorySlug: 'sourcils-cils',
    agendaSourceId: 86323,
    name: 'Teinture cils',
    description: null,
    durationMinutes: 40,
    priceCents: 3000,
    priceNote: null,
    color: '#bbdefb',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/8864/original/Capture_d%E2%80%99e%CC%81cran_2024-04-22_a%CC%80_15.40.28.png?1713793259',
  },
  {
    slug: 'sourcils-cils-teinture-sourcils',
    categorySlug: 'sourcils-cils',
    agendaSourceId: 86326,
    name: 'Teinture sourcils',
    description: null,
    durationMinutes: 40,
    priceCents: 4000,
    priceNote: null,
    color: '#2196f3',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/8872/original/Capture_d%E2%80%99e%CC%81cran_2024-04-22_a%CC%80_15.40.28.png?1713793472',
  },
  {
    slug: 'sourcils-cils-teinture-cils-sourcils',
    categorySlug: 'sourcils-cils',
    agendaSourceId: 86327,
    name: 'Teinture cils + sourcils',
    description: null,
    durationMinutes: 60,
    priceCents: 4000,
    priceNote: '60 CHF avec l’épilation',
    color: '#b3e5fc',
    sortOrder: 2,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/8879/original/Capture_d%E2%80%99e%CC%81cran_2024-04-22_a%CC%80_15.46.41.png?1713793613',
  },
  {
    slug: 'sourcils-cils-teinture-epilation-fil',
    categorySlug: 'sourcils-cils',
    agendaSourceId: 86329,
    name: 'Teinture + épilation au fil',
    description: null,
    durationMinutes: 30,
    priceCents: 4000,
    priceNote: null,
    color: '#3e2723',
    sortOrder: 3,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/8880/original/Capture_d%E2%80%99e%CC%81cran_2024-04-15_a%CC%80_16.17.49.png?1713793978',
  },
  {
    slug: 'sourcils-cils-microblading',
    categorySlug: 'sourcils-cils',
    agendaSourceId: 84652,
    name: 'Microblading',
    description:
      'Transformez vos sourcils avec notre service de microblading, retouche comprise.',
    durationMinutes: 180,
    priceCents: 45000,
    priceNote: 'Retouche comprise',
    color: '#bca4c0',
    sortOrder: 4,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/12394/original/Capture_d%E2%80%99e%CC%81cran_2024-02-28_a%CC%80_09.55.24.png?1709110539',
  },
  {
    slug: 'sourcils-cils-microshading',
    categorySlug: 'sourcils-cils',
    agendaSourceId: 86325,
    name: 'Microshading',
    description: null,
    durationMinutes: 150,
    priceCents: 28000,
    priceNote: 'Retouche comprise',
    color: '#3f51b5',
    sortOrder: 5,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/8869/original/Capture_d%E2%80%99e%CC%81cran_2024-04-15_a%CC%80_16.21.07.png?1713793457',
  },
  {
    slug: 'epilation-fil-sourcils',
    categorySlug: 'epilation-au-fil',
    agendaSourceId: 84574,
    name: 'Sourcils',
    description: null,
    durationMinutes: 30,
    priceCents: 2500,
    priceNote: null,
    color: '#f8bbd0',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11972/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_11.19.15.png?1709029185',
  },
  {
    slug: 'epilation-fil-levre',
    categorySlug: 'epilation-au-fil',
    agendaSourceId: 84575,
    name: 'Lèvre',
    description: null,
    durationMinutes: 30,
    priceCents: 1500,
    priceNote: null,
    color: '#f48fb1',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/4578/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_11.21.42.png?1709029321',
  },
  {
    slug: 'epilation-fil-visage-complet',
    categorySlug: 'epilation-au-fil',
    agendaSourceId: 84576,
    name: 'Visage complet',
    description: null,
    durationMinutes: 30,
    priceCents: 6000,
    priceNote: null,
    color: '#e77fa2',
    sortOrder: 2,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/4586/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_11.21.21.png?1709029359',
  },
  {
    slug: 'epilation-dielectrique-tarif',
    categorySlug: 'epilation-dielectrique',
    agendaSourceId: null,
    name: 'Tarif',
    description:
      'Cette prestation sera ouverte à la réservation dès que sa durée de séance aura été confirmée.',
    durationMinutes: 1,
    priceCents: 200,
    priceNote: '/ min',
    color: '#927b59',
    sortOrder: 0,
    isBookable: false,
    sourceImageUrl: null,
  },
  {
    slug: 'epilation-laser-visage',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84564,
    name: 'Visage',
    description: null,
    durationMinutes: 30,
    priceCents: 10000,
    priceNote: null,
    color: '#b69a90',
    sortOrder: 0,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11957/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.13.10.png?1709025335',
  },
  {
    slug: 'epilation-laser-aisselles',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84565,
    name: 'Aisselles',
    description: null,
    durationMinutes: 30,
    priceCents: 12000,
    priceNote: null,
    color: '#a7867a',
    sortOrder: 1,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11960/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.17.52.png?1709025486',
  },
  {
    slug: 'epilation-laser-bikini',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84569,
    name: 'Bikini',
    description: null,
    durationMinutes: 30,
    priceCents: 15000,
    priceNote: null,
    color: '#3e2723',
    sortOrder: 2,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/12242/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.52.58.png?1709027672',
  },
  {
    slug: 'epilation-laser-demi-jambes',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84567,
    name: 'Demi-jambes',
    description: null,
    durationMinutes: 60,
    priceCents: 17000,
    priceNote: null,
    color: '#7c6159',
    sortOrder: 3,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11962/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.40.51.png?1709026937',
  },
  {
    slug: 'epilation-laser-jambes-completes',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84568,
    name: 'Jambes complètes',
    description: null,
    durationMinutes: 120,
    priceCents: 29000,
    priceNote: null,
    color: '#6f554c',
    sortOrder: 4,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11967/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.45.09.png?1709027131',
  },
  {
    slug: 'epilation-laser-bras',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84566,
    name: 'Bras',
    description: null,
    durationMinutes: 45,
    priceCents: 18000,
    priceNote: null,
    color: '#937367',
    sortOrder: 5,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11974/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.23.53.png?1709025850',
  },
  {
    slug: 'epilation-laser-dos',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84573,
    name: 'Dos',
    description: null,
    durationMinutes: 60,
    priceCents: 17000,
    priceNote: null,
    color: '#3c3560',
    sortOrder: 6,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11971/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_10.59.42.png?1709028988',
  },
  {
    slug: 'epilation-laser-torse',
    categorySlug: 'epilation-laser',
    agendaSourceId: 84572,
    name: 'Torse',
    description: null,
    durationMinutes: 60,
    priceCents: 19000,
    priceNote: null,
    color: '#4b4371',
    sortOrder: 7,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/11973/original/Capture_d%E2%80%99e%CC%81cran_2024-02-27_a%CC%80_11.02.08.png?1709028554',
  },
  {
    slug: 'epilation-laser-corps-entier',
    categorySlug: 'epilation-laser',
    agendaSourceId: 85093,
    name: 'Corps entier',
    description: null,
    durationMinutes: 120,
    priceCents: 55000,
    priceNote: null,
    color: '#8983c9',
    sortOrder: 8,
    isBookable: true,
    sourceImageUrl:
      'https://thumbs.agenda.ch/uploads/service_pictures/13688/original/Capture_d%E2%80%99e%CC%81cran_2024-03-05_a%CC%80_16.58.35.png?1709654432',
  },
]
